### ISSUE TITLE
pysam version

### ISSUE THREAD

**Issue by TimoTrefzer** [sridnona/cb_sniffer#1]
Hello,

I was wondering which version of pysam you are using. 
Because I get the following error and think it might be due to changes in pysams variables:

File "scripts/cb_sniffer.py", line 347, in <module>
    barcode_counts = x.count_barcodes(bam_file, bars, x.classify(), mq, bq)
  File "scripts/cb_sniffer.py", line 77, in count_barcodes
    with pysam.AlignmentFile(bam_fil, 'rb') as pile:
AttributeError: 'module' object has no attribute 'AlignmentFile'

Cheers

**Comment by TimoTrefzer** [comment]
For me it worked now with version 0.15.3 from bioconda

**Comment by sridnona** [comment]
hi @TimoTrefzer 

If you look at the code line6-7 
#print(pysam.__version__)
#0.14.1

the docker container attached has the same same version, please let me know if you still have issues. 

Thanks
Sid

**Comment by sridnona** [comment]
Hi @TimoTrefzer closing this happy to reopen it if you still see issues. 

Thanks
Sid
